# Generated by Django 6.0.6 on 2026-06-21 21:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_presentation_project_presentation_pass_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationresult',
            name='criteria_total',
            field=models.FloatField(blank=True, help_text='Auto-calculated total from criteria scores', null=True),
        ),
        migrations.AddField(
            model_name='presentationresult',
            name='is_graded_by_criteria',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PresentationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the criteria (e.g., 'Comment Implementation', 'Type')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the criteria', null=True)),
                ('criteria_type', models.CharField(choices=[('numeric', 'Numeric Score'), ('dropdown', 'Dropdown Selection'), ('text', 'Text Feedback')], default='numeric', max_length=20)),
                ('max_score', models.FloatField(default=10.0, help_text='Maximum score for this criteria')),
                ('weight', models.FloatField(default=1.0, help_text='Weight of this criteria in total score')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this criteria is required for grading')),
                ('options', models.JSONField(blank=True, default=list, help_text="Options for dropdown: [{'label': 'Embedded', 'value': 2.5}, {'label': 'Web App', 'value': 1.5}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='projects.presentation')),
            ],
            options={
                'verbose_name_plural': 'Presentation Criteria',
                'ordering': ['order', 'name'],
                'unique_together': {('presentation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PresentationResultCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='Score given for this criteria', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('selected_option', models.CharField(blank=True, help_text="Selected option from dropdown (e.g., 'Embedded', 'Good progress')", max_length=100, null=True)),
                ('comment', models.TextField(blank=True, help_text='Feedback for this specific criteria', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.presentationcriteria')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='projects.presentationresult')),
            ],
            options={
                'verbose_name_plural': 'Presentation Criteria Scores',
                'unique_together': {('result', 'criteria')},
            },
        ),
    ]
