# Generated by Django 5.2 on 2026-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_presentationresult_criteria_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duplicate_keywords_matched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
