# Generated by Django 5.2 on 2026-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_duplicate_keywords_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentor_comment',
            field=models.TextField(blank=True, help_text="Mentor's feedback on the project", null=True),
        ),
    ]
