# Generated by Django 6.0.6 on 2026-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
        ('projects', '0008_project_mentor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Maximum number of students this mentor can handle', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_bio',
            field=models.TextField(blank=True, help_text="Brief description of mentor's expertise and experience", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, help_text='Project types this mentor specializes in', related_name='specialist_mentors', to='projects.projecttype'),
        ),
    ]
