# Generated by Django 6.0.6 on 2026-07-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_max_students_user_mentor_bio_and_more'),
        ('projects', '0008_project_mentor_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specializations',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Project type this mentor specializes in (select ONE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_mentors', to='projects.projecttype'),
        ),
    ]
